GET http://localhost:8080/news/hotNews/getHotNewsAndCommentById?id=2
Accept: application/json

###
GET http://localhost:8080/news/hotNews/search?title=大
Accept: application/json

###
GET http://localhost:8080/news/hotNews/getAll
Accept: application/json

###
