GET http://localhost:8080/news/user/getImage
Accept: application/json

###
GET http://localhost:8080/news/comment/getCommentByhotNewsId?hotNewsId=1
Accept: application/json

###
###
PUT http://localhost:8080/news/comment/addComment
Content-Type: application/json

{
    "hot_news_id": 1,
    "content": "这是第二条评论"
}

###
GET http://localhost:8080/news/hotNews/getHotNewsAndCommentById?id=1
Accept: application/json

###
GET http://localhost:8080/news/hotNews/search?title=大
Accept: application/json

###
GET http://localhost:8080/news/hotNews/getAll
Accept: application/json

###
